// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cve.sql

package repository

import (
	"context"
)

const listCves = `-- name: ListCves :many
SELECT c.id, c.title, c.description, c.serial, c.is_rejected, c.assigner_org_id, c.assigner_short_name, c.date_reserved, c.date_published, c.date_updated, c.date_assigned, c.date_public FROM cve As c ORDER BY c.name DESC
`

type ListCvesRow struct {
	Cve Cve `json:"cve"`
}

func (q *Queries) ListCves(ctx context.Context) ([]ListCvesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCves)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCvesRow
	for rows.Next() {
		var i ListCvesRow
		if err := rows.Scan(
			&i.Cve.ID,
			&i.Cve.Title,
			&i.Cve.Description,
			&i.Cve.Serial,
			&i.Cve.IsRejected,
			&i.Cve.AssignerOrgID,
			&i.Cve.AssignerShortName,
			&i.Cve.DateReserved,
			&i.Cve.DatePublished,
			&i.Cve.DateUpdated,
			&i.Cve.DateAssigned,
			&i.Cve.DatePublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
