// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cve.sql

package repository

import (
	"context"
)

const listCVEs = `-- name: ListCVEs :many
SELECT id, title, description, serial, is_rejected, assigner_org_id, assigner_short_name, date_reserved, date_published, date_updated, date_assigned, date_public FROM cve ORDER BY name DESC
`

func (q *Queries) ListCVEs(ctx context.Context) ([]Cve, error) {
	rows, err := q.db.QueryContext(ctx, listCVEs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cve
	for rows.Next() {
		var i Cve
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Serial,
			&i.IsRejected,
			&i.AssignerOrgID,
			&i.AssignerShortName,
			&i.DateReserved,
			&i.DatePublished,
			&i.DateUpdated,
			&i.DateAssigned,
			&i.DatePublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
