// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: debiantriage.sql

package repository

import (
	"context"

	debtriage "github.com/gardenlinux/glvd2/internal/model/debtriage"
)

const getDebianTriage = `-- name: GetDebianTriage :one
SELECT cve_id, status, not_for_us, notes, to_dos FROM debian_triage WHERE cve_id = ? LIMIT 1
`

func (q *Queries) GetDebianTriage(ctx context.Context, cveID string) (DebianTriage, error) {
	row := q.db.QueryRowContext(ctx, getDebianTriage, cveID)
	var i DebianTriage
	err := row.Scan(
		&i.CVEID,
		&i.Status,
		&i.NotForUs,
		&i.Notes,
		&i.ToDos,
	)
	return i, err
}

const insertDebianPackageOrIgnore = `-- name: InsertDebianPackageOrIgnore :one
INSERT OR IGNORE INTO debian_package(name) VALUES (?) RETURNING name
`

func (q *Queries) InsertDebianPackageOrIgnore(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, insertDebianPackageOrIgnore, name)
	err := row.Scan(&name)
	return name, err
}

const insertDebianReleaseOrIgnore = `-- name: InsertDebianReleaseOrIgnore :one
INSERT OR IGNORE INTO debian_release(name) VALUES (?) RETURNING name
`

func (q *Queries) InsertDebianReleaseOrIgnore(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, insertDebianReleaseOrIgnore, name)
	err := row.Scan(&name)
	return name, err
}

const insertDebianTriage = `-- name: InsertDebianTriage :one
INSERT INTO debian_triage(cve_id, status, not_for_us, notes, to_dos) VALUES (?, ?, ?, ?, ?) RETURNING cve_id, status, not_for_us, notes, to_dos
`

type InsertDebianTriageParams struct {
	CVEID    string               `json:"cve_id"`
	Status   debtriage.StatusType `json:"status"`
	NotForUs string               `json:"not_for_us"`
	Notes    string               `json:"notes"`
	ToDos    string               `json:"to_dos"`
}

func (q *Queries) InsertDebianTriage(ctx context.Context, arg InsertDebianTriageParams) (DebianTriage, error) {
	row := q.db.QueryRowContext(ctx, insertDebianTriage,
		arg.CVEID,
		arg.Status,
		arg.NotForUs,
		arg.Notes,
		arg.ToDos,
	)
	var i DebianTriage
	err := row.Scan(
		&i.CVEID,
		&i.Status,
		&i.NotForUs,
		&i.Notes,
		&i.ToDos,
	)
	return i, err
}

const insertDebianTriageAffectedPackage = `-- name: InsertDebianTriageAffectedPackage :one
INSERT INTO debian_triage_affected_package(cve_id, package_name, version, info) VALUES (?, ?, ?, ?) RETURNING id, cve_id, package_name, version, info
`

type InsertDebianTriageAffectedPackageParams struct {
	CVEID       string  `json:"cve_id"`
	PackageName string  `json:"package_name"`
	Version     string  `json:"version"`
	Info        *string `json:"info"`
}

func (q *Queries) InsertDebianTriageAffectedPackage(ctx context.Context, arg InsertDebianTriageAffectedPackageParams) (DebianTriageAffectedPackage, error) {
	row := q.db.QueryRowContext(ctx, insertDebianTriageAffectedPackage,
		arg.CVEID,
		arg.PackageName,
		arg.Version,
		arg.Info,
	)
	var i DebianTriageAffectedPackage
	err := row.Scan(
		&i.ID,
		&i.CVEID,
		&i.PackageName,
		&i.Version,
		&i.Info,
	)
	return i, err
}

const insertDebianTriageAffectedRelease = `-- name: InsertDebianTriageAffectedRelease :one
INSERT INTO debian_triage_affected_release(cve_id, release_name, package_name, action, info) VALUES (?, ?, ?, ?, ?) RETURNING id, cve_id, release_name, package_name, "action", info
`

type InsertDebianTriageAffectedReleaseParams struct {
	CVEID       string  `json:"cve_id"`
	ReleaseName string  `json:"release_name"`
	PackageName string  `json:"package_name"`
	Action      string  `json:"action"`
	Info        *string `json:"info"`
}

func (q *Queries) InsertDebianTriageAffectedRelease(ctx context.Context, arg InsertDebianTriageAffectedReleaseParams) (DebianTriageAffectedRelease, error) {
	row := q.db.QueryRowContext(ctx, insertDebianTriageAffectedRelease,
		arg.CVEID,
		arg.ReleaseName,
		arg.PackageName,
		arg.Action,
		arg.Info,
	)
	var i DebianTriageAffectedRelease
	err := row.Scan(
		&i.ID,
		&i.CVEID,
		&i.ReleaseName,
		&i.PackageName,
		&i.Action,
		&i.Info,
	)
	return i, err
}

const listAffectedPackagesForDebianTriage = `-- name: ListAffectedPackagesForDebianTriage :many
SELECT id, cve_id, package_name, version, info FROM debian_triage_affected_package WHERE cve_id = ? ORDER BY id ASC
`

func (q *Queries) ListAffectedPackagesForDebianTriage(ctx context.Context, cveID string) ([]DebianTriageAffectedPackage, error) {
	rows, err := q.db.QueryContext(ctx, listAffectedPackagesForDebianTriage, cveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DebianTriageAffectedPackage
	for rows.Next() {
		var i DebianTriageAffectedPackage
		if err := rows.Scan(
			&i.ID,
			&i.CVEID,
			&i.PackageName,
			&i.Version,
			&i.Info,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAffectedReleasesForDebianTriage = `-- name: ListAffectedReleasesForDebianTriage :many
SELECT id, cve_id, release_name, package_name, "action", info FROM debian_triage_affected_release WHERE cve_id = ? ORDER BY id ASC
`

func (q *Queries) ListAffectedReleasesForDebianTriage(ctx context.Context, cveID string) ([]DebianTriageAffectedRelease, error) {
	rows, err := q.db.QueryContext(ctx, listAffectedReleasesForDebianTriage, cveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DebianTriageAffectedRelease
	for rows.Next() {
		var i DebianTriageAffectedRelease
		if err := rows.Scan(
			&i.ID,
			&i.CVEID,
			&i.ReleaseName,
			&i.PackageName,
			&i.Action,
			&i.Info,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebianTriages = `-- name: ListDebianTriages :many
SELECT cve_id, status, not_for_us, notes, to_dos FROM debian_triage ORDER BY cve_id DESC
`

func (q *Queries) ListDebianTriages(ctx context.Context) ([]DebianTriage, error) {
	rows, err := q.db.QueryContext(ctx, listDebianTriages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DebianTriage
	for rows.Next() {
		var i DebianTriage
		if err := rows.Scan(
			&i.CVEID,
			&i.Status,
			&i.NotForUs,
			&i.Notes,
			&i.ToDos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
