// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

type Affect struct {
	ID    int64   `json:"id"`
	CveID *string `json:"cve_id"`
}

type Cve struct {
	ID                string  `json:"id"`
	Title             *string `json:"title"`
	Description       *string `json:"description"`
	Serial            int64   `json:"serial"`
	IsRejected        int64   `json:"is_rejected"`
	AssignerOrgID     *string `json:"assigner_org_id"`
	AssignerShortName *string `json:"assigner_short_name"`
	DateReserved      *string `json:"date_reserved"`
	DatePublished     *string `json:"date_published"`
	DateUpdated       *string `json:"date_updated"`
	DateAssigned      *string `json:"date_assigned"`
	DatePublic        *string `json:"date_public"`
}

type CvssMetric struct {
	ID           int64    `json:"id"`
	CveID        *string  `json:"cve_id"`
	Issuer       *string  `json:"issuer"`
	Version      *string  `json:"version"`
	VectorString *string  `json:"vector_string"`
	BaseScore    *float64 `json:"base_score"`
	BaseSeverity *string  `json:"base_severity"`
}

type Product struct {
	ID    int64   `json:"id"`
	Title *string `json:"title"`
	Cpe   *string `json:"cpe"`
}
