// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	debtriage "github.com/gardenlinux/glvd2/internal/model/debtriage"
)

type Affect struct {
	ID        int64   `json:"id"`
	CVEID     *string `json:"cve_id"`
	ProductID *int64  `json:"product_id"`
}

type Cve struct {
	ID                string  `json:"id"`
	Title             *string `json:"title"`
	Description       *string `json:"description"`
	Serial            int64   `json:"serial"`
	IsRejected        int64   `json:"is_rejected"`
	AssignerOrgID     *string `json:"assigner_org_id"`
	AssignerShortName *string `json:"assigner_short_name"`
	DateReserved      *string `json:"date_reserved"`
	DatePublished     *string `json:"date_published"`
	DateUpdated       *string `json:"date_updated"`
	DateAssigned      *string `json:"date_assigned"`
	DatePublic        *string `json:"date_public"`
}

type CvssMetric struct {
	ID           int64    `json:"id"`
	CVEID        *string  `json:"cve_id"`
	Issuer       *string  `json:"issuer"`
	Version      *string  `json:"version"`
	VectorString *string  `json:"vector_string"`
	BaseScore    *float64 `json:"base_score"`
	BaseSeverity *string  `json:"base_severity"`
}

type DebianPackage struct {
	Name string `json:"name"`
}

type DebianRelease struct {
	Name string `json:"name"`
}

type DebianTriage struct {
	CVEID    string               `json:"cve_id"`
	Status   debtriage.StatusType `json:"status"`
	NotForUs string               `json:"not_for_us"`
	Notes    string               `json:"notes"`
	ToDos    string               `json:"to_dos"`
}

type DebianTriageAffectedPackage struct {
	ID          int64   `json:"id"`
	CVEID       string  `json:"cve_id"`
	PackageName string  `json:"package_name"`
	Version     string  `json:"version"`
	Info        *string `json:"info"`
}

type DebianTriageAffectedRelease struct {
	ID          int64   `json:"id"`
	CVEID       string  `json:"cve_id"`
	ReleaseName string  `json:"release_name"`
	PackageName string  `json:"package_name"`
	Action      string  `json:"action"`
	Info        *string `json:"info"`
}

type Product struct {
	ID    int64   `json:"id"`
	Title *string `json:"title"`
	CPE   *string `json:"cpe"`
}
